AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GraphQL:
    Properties:
      CodeUri: s3://csn-api/a4977c94749a8bc0f172bd64d5e58554
      Events:
        AnyRequest:
          Properties:
            Method: ANY
            Path: /api
          Type: Api
      Handler: index.handle
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
